def questions(question, answer):
    my_file = open("my_file.txt", "a")
    my_file.write(question)
    my_file.write(answer)
    my_file.write("\n")
    my_file.close()


name = input("Name: ")
questions("Your name: ", name)
address = input("Address: ")
questions("Your address: ", address)
college_name = input("College name: ")
questions("Your college name: ", college_name)
campus_name = input("Campus name: ")
questions("Your campus name: ", campus_name)
age = input("Age: ")
questions("Your age: ", age)
mode_of_trans = input("Mode of transport: ")
questions("Your mode of transport: ", mode_of_trans)
travel_time = input("Travel time: ")
questions("Your travel time: ", travel_time)
travel_cost = input("Travel cost: ")
questions("Your travel cost: ", travel_cost)
trans_company = input("Company of transport: ")
questions("Your transport's company name: ", trans_company)
transport_like = input("Do your like your current method of transport: ")
questions("Di you like your current mode of transport?: ", transport_like)
